//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner_product
    {
        public int ID { get; set; }
        public int FK_Partner { get; set; }
        public int FK_Product { get; set; }
        public int FK_Sotrudnik { get; set; }
        public int Kolichestvo { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Partner Partner { get; set; }
        public virtual Product Product { get; set; }
        public virtual Sotrudnik Sotrudnik { get; set; }
    }
}
