//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partner()
        {
            this.Partner_product = new HashSet<Partner_product>();
        }
    
        public int ID_Partner { get; set; }
        public string Nazvanie { get; set; }
        public string Address { get; set; }
        public string INN { get; set; }
        public string E_mail { get; set; }
        public string Telephone { get; set; }
        public string Director { get; set; }
        public int Rayting { get; set; }
        public string Logotype { get; set; }
        public int FK_Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partner_product> Partner_product { get; set; }
        public virtual Type_partner Type_partner { get; set; }
    }
}
