//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_material
    {
        public int ID { get; set; }
        public int FK_Product { get; set; }
        public int FK_Material { get; set; }
        public int Kolichestvo { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Material Material { get; set; }
    }
}
