//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Partner_product = new HashSet<Partner_product>();
            this.Product_material = new HashSet<Product_material>();
        }
    
        public int ID_Product { get; set; }
        public string Nazvanie { get; set; }
        public int FK_Type { get; set; }
        public Nullable<double> Visota { get; set; }
        public Nullable<double> Shirina { get; set; }
        public Nullable<double> Dlina { get; set; }
        public Nullable<double> massa_netto { get; set; }
        public Nullable<double> massa { get; set; }
        public double Stoimost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partner_product> Partner_product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_material> Product_material { get; set; }
        public virtual Type_product Type_product { get; set; }
    }
}
