//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sotrudnik()
        {
            this.Partner_product = new HashSet<Partner_product>();
        }
    
        public int ID_Sotrudnik { get; set; }
        public string Imya { get; set; }
        public string Familia { get; set; }
        public string Otchestvo { get; set; }
        public System.DateTime Data_rozdenia { get; set; }
        public string bank { get; set; }
        public string seria_passport { get; set; }
        public string nomer_passport { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partner_product> Partner_product { get; set; }
    }
}
